### PR TITLE
Added foods and weather

### PR DESCRIPTION
**Pull request by andrew-anguiano**
Broke foods into a separate object so it could be better sorted.

### CODE REVIEW

**Comment by mog13** [comment]
thanks, good idea it will be more usable in smaller categories like this! :)
(Im thinking we could even ad a' food.all' which contained templates linking to all subcategories)

i saw some duplicates whilst looking, i don't think you added them but i added a commit to this pull request to remove them, hope you dont mind :)

**Comment by ecodonohoe** [comment]
@andrew-anguiano you're missing a few commas in some of your lists. I did the same thing..

**Comment by mog13** [comment]
@ecodonohoe ahh thanks for the spot, am only able to check on mobile ATM so its hard to see syntax issues! Appreciate you giving it a lookover and highlighting it :)

**Comment by andrew-anguiano** [comment]
@ecodonohoe d'oh! thanks for the catch 😄

**Pull request merged**
